"use client";
import Link from "next/link";
import { Suspense, useEffect, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { AppShell } from "@/components/AppShell";
import { supabase } from "@/lib/supabase";
import { useAnonAuth } from "@/lib/useAnonAuth";
import { Task } from "@/lib/types";
type Book = { book_key:string; title:string; author:string|null; confirmed:boolean; task_count:number; done_count:number; processing_count:number; failed_count:number; review_count:number; final_count:number; recent_updated_at:string; latest_task_id:string; total_count:number };
const PAGE_SIZE=20;
function Content(){
 const {userId,error:authError}=useAnonAuth(); const router=useRouter(); const search=useSearchParams();
 const [books,setBooks]=useState<Book[]>([]),[tasks,setTasks]=useState<Task[]>([]),[query,setQuery]=useState(search.get("q")||""),[status,setStatus]=useState(search.get("status")||"all"),[page,setPage]=useState(Math.max(1,Number(search.get("page")||1))),[selected,setSelected]=useState<Book|null>(null),[title,setTitle]=useState(""),[loading,setLoading]=useState(false),[message,setMessage]=useState<string|null>(null),[confirming,setConfirming]=useState(false);
 const load=async()=>{setLoading(true);const {data,error}=await supabase.rpc("book_library",{p_query:query.trim()||null,p_status:status,p_limit:PAGE_SIZE,p_offset:(page-1)*PAGE_SIZE});if(error)setMessage(`书籍库加载失败：${error.message}`);else setBooks((data||[]) as Book[]);setLoading(false)};
 useEffect(()=>{if(userId)load()},[userId,query,status,page]); useEffect(()=>{const p=new URLSearchParams();if(query.trim())p.set("q",query.trim());if(status!=="all")p.set("status",status);if(page>1)p.set("page",String(page));router.replace(p.toString()?`/book-library?${p}`:"/book-library",{scroll:false})},[query,status,page,router]);
 const open=async(b:Book)=>{setSelected(b);setTitle(b.confirmed?b.title:"");const {data}=await supabase.rpc("book_library_tasks",{p_book_key:b.book_key});setTasks((data||[]) as Task[])};
 const confirm=async()=>{if(!selected||!title.trim()||confirming)return;setConfirming(true);const {data,error}=await supabase.rpc("confirm_book_library_candidate",{p_book_key:selected.book_key,p_title:title.trim(),p_author:selected.author});setConfirming(false);if(error)setMessage(`确认失败：${error.message}`);else{setMessage(`已确认并归并 ${data||0} 条书籍信号`);setSelected(null);load()}};
 if(!userId&&!authError)return <AppShell><div className="page-loading"><div className="skeleton loading-block"/></div></AppShell>; if(authError)return <AppShell><div className="state-panel error-state"><strong>连接工作区失败</strong><span>{authError}</span></div></AppShell>;
 const total=books[0]?.total_count||0,pages=Math.max(1,Math.ceil(total/PAGE_SIZE)); return <AppShell><div className="library-page anim-fade-in"><header className="collection-heading"><div><p className="eyebrow">知识资产</p><h1>书籍库</h1><p>按确认书名聚合跨任务内容，低置信候选会保留为待确认记录。</p></div><Link className="secondary-action" href="/video-collection">查看视频采集</Link></header><section className="library-toolbar"><input value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}} placeholder="搜索书名或作者" aria-label="搜索书名或作者"/><select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}} aria-label="筛选书籍状态"><option value="all">全部书籍</option><option value="confirmed">已确认</option><option value="candidate">待确认候选</option></select><span>{total} 本</span></section>{message&&<p className="collection-notice" role="status">{message}</p>}{loading&&<div className="collection-loading" role="status">正在更新书籍库…</div>}{books.length?<div className="library-grid">{books.map(b=><article className="library-card" key={b.book_key} onClick={()=>open(b)}><div className="library-card-top"><span className="book-glyph">▤</span><span className={`library-confidence ${b.confirmed?"confirmed":"candidate"}`}>{b.confirmed?"已确认":"待确认"}</span></div><h2>{b.title}</h2><p>{b.author||"作者待补充"}</p><dl><div><dt>任务</dt><dd>{b.task_count}</dd></div><div><dt>成片</dt><dd>{b.final_count}</dd></div><div><dt>处理中</dt><dd>{b.processing_count}</dd></div><div><dt>异常</dt><dd>{b.failed_count}</dd></div></dl><footer><span>更新于 {new Date(b.recent_updated_at).toLocaleDateString("zh-CN")}</span><Link href={`/task/${b.latest_task_id}`} onClick={e=>e.stopPropagation()}>打开任务</Link></footer></article>)}</div>:!loading&&<div className="state-panel"><strong>还没有书籍信号</strong><span>完成逐字稿后，系统会把明确提及的书名收录到这里。</span><Link className="primary-action" href="/video-collection">前往视频采集</Link></div>}{total>0&&<div className="collection-pagination"><span>第 {page} / {pages} 页</span><button className="secondary-action" disabled={page<=1} onClick={()=>setPage(page-1)}>上一页</button><button className="secondary-action" disabled={page>=pages} onClick={()=>setPage(page+1)}>下一页</button></div>}{selected&&<div className="library-drawer-backdrop" onClick={()=>setSelected(null)}><aside className="library-drawer" onClick={e=>e.stopPropagation()}><header><div><p className="eyebrow">书籍详情</p><h2>{selected.title}</h2></div><button className="icon-button" onClick={()=>setSelected(null)} aria-label="关闭详情">×</button></header><p>{selected.author||"作者待补充"} · {selected.task_count} 个关联任务</p><div className="library-task-list">{tasks.map(t=><Link key={t.id} href={`/task/${t.id}`}><span>{t.title||t.id}</span><small>{t.status}</small></Link>)}</div><label className="library-confirm-field">确认书名<input value={title} onChange={e=>setTitle(e.target.value)}/></label><button className="primary-action" disabled={confirming||!title.trim()} onClick={confirm}>{confirming?"保存中…":"确认并聚合"}</button></aside></div>}</div></AppShell>;
}
export default function BookLibraryPage(){return <Suspense fallback={<AppShell><div className="page-loading"><div className="skeleton loading-block"/></div></AppShell>}><Content/></Suspense>}
